export type PublicApiWorkflow =
  | 'lead-enrichment'
  | 'local-seo'
  | 'content-intelligence'
  | 'campaign-delivery'
  | 'creative-production'
  | 'ops-safety'

export interface PublicApiCatalogItem {
  name: string
  url: string
  sourceCategory: string
  auth: 'No' | 'apiKey' | 'OAuth' | 'User-Agent'
  workflow: PublicApiWorkflow
  platformUse: string
  description: string
}

export const PUBLIC_API_CATALOG_SOURCE = {
  name: 'public-apis/public-apis',
  url: 'https://github.com/public-apis/public-apis',
  rawUrl: 'https://raw.githubusercontent.com/public-apis/public-apis/master/README.md',
} as const

export const MARKETING_PUBLIC_APIS: PublicApiCatalogItem[] = [
  {
    name: 'Clearbit Logo',
    url: 'https://clearbit.com/docs#logo-api',
    sourceCategory: 'Business',
    auth: 'apiKey',
    workflow: 'lead-enrichment',
    platformUse: 'Attach company logos to lead, client, and proposal views.',
    description: 'Search for company logos and embed them in your projects',
  },
  {
    name: 'Domainsdb.info',
    url: 'https://domainsdb.info/',
    sourceCategory: 'Business',
    auth: 'No',
    workflow: 'lead-enrichment',
    platformUse: 'Find related domains for prospect research and competitor discovery.',
    description: 'Registered Domain Names Search',
  },
  {
    name: 'Tomba email finder',
    url: 'https://tomba.io/api',
    sourceCategory: 'Business',
    auth: 'apiKey',
    workflow: 'lead-enrichment',
    platformUse: 'Find and verify B2B prospect emails before Ryan reaches out.',
    description: 'Email Finder for B2B sales and email marketing and email verifier',
  },
  {
    name: 'Hunter',
    url: 'https://hunter.io/api',
    sourceCategory: 'Development',
    auth: 'apiKey',
    workflow: 'lead-enrichment',
    platformUse: 'Domain search, author lookup, and email verification for outbound prospecting.',
    description: 'API for domain search, professional email finder, author finder and email verifier',
  },
  {
    name: 'Yelp',
    url: 'https://www.yelp.com/developers/documentation/v3',
    sourceCategory: 'Open Data',
    auth: 'OAuth',
    workflow: 'local-seo',
    platformUse: 'Discover local competitors and enrich service-area market snapshots.',
    description: 'Find Local Business',
  },
  {
    name: 'Geoapify',
    url: 'https://www.geoapify.com/api/geocoding-api/',
    sourceCategory: 'Geocoding',
    auth: 'apiKey',
    workflow: 'local-seo',
    platformUse: 'Geocode client/prospect addresses and build city/service territory intelligence.',
    description: 'Forward and reverse geocoding, address autocomplete',
  },
  {
    name: 'Nominatim',
    url: 'https://nominatim.org/release-docs/latest/api/Overview/',
    sourceCategory: 'Geocoding',
    auth: 'No',
    workflow: 'local-seo',
    platformUse: 'No-key fallback for geocoding local service-area checks.',
    description: 'Provides worldwide forward / reverse geocoding',
  },
  {
    name: 'Lob.com',
    url: 'https://lob.com/',
    sourceCategory: 'Data Validation',
    auth: 'apiKey',
    workflow: 'lead-enrichment',
    platformUse: 'Validate US business addresses before campaign or direct-mail workflows.',
    description: 'US Address Verification',
  },
  {
    name: 'Disify',
    url: 'https://www.disify.com/',
    sourceCategory: 'Email',
    auth: 'No',
    workflow: 'lead-enrichment',
    platformUse: 'Reject disposable emails in public lead capture and partner referrals.',
    description: 'Validate and detect disposable and temporary email addresses',
  },
  {
    name: 'EmailRep',
    url: 'https://docs.emailrep.io/',
    sourceCategory: 'Security',
    auth: 'No',
    workflow: 'ops-safety',
    platformUse: 'Score inbound lead email risk before autonomous follow-up.',
    description: 'Email address threat and risk prediction',
  },
  {
    name: 'Numverify',
    url: 'https://numverify.com?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers',
    sourceCategory: 'Phone',
    auth: 'apiKey',
    workflow: 'lead-enrichment',
    platformUse: 'Validate phone numbers before assigning Ryan call tasks.',
    description: 'Phone number validation',
  },
  {
    name: 'Veriphone',
    url: 'https://veriphone.io',
    sourceCategory: 'Phone',
    auth: 'apiKey',
    workflow: 'lead-enrichment',
    platformUse: 'Phone validation and carrier lookup for sales outreach hygiene.',
    description: 'Phone number validation & carrier lookup',
  },
  {
    name: 'Microlink.io',
    url: 'https://microlink.io',
    sourceCategory: 'Open Data',
    auth: 'No',
    workflow: 'content-intelligence',
    platformUse: 'Extract metadata from client, competitor, and prospect URLs.',
    description: 'Extract structured data from any website',
  },
  {
    name: 'LinkPreview',
    url: 'https://www.linkpreview.net',
    sourceCategory: 'Open Data',
    auth: 'apiKey',
    workflow: 'content-intelligence',
    platformUse: 'Generate link previews for client snapshots, prospect briefs, and content audits.',
    description: 'Get JSON formatted summary with title, description and preview image for any requested URL',
  },
  {
    name: 'Screenshotlayer',
    url: 'https://screenshotlayer.com?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers',
    sourceCategory: 'Photography',
    auth: 'No',
    workflow: 'content-intelligence',
    platformUse: 'Capture client/competitor screenshots for audit evidence.',
    description: 'URL to screenshot',
  },
  {
    name: 'ApiFlash',
    url: 'https://apiflash.com/',
    sourceCategory: 'Development',
    auth: 'apiKey',
    workflow: 'content-intelligence',
    platformUse: 'Screenshot fallback for visual website audits and before/after proof.',
    description: 'Chrome based screenshot API for developers',
  },
  {
    name: 'GeoScore',
    url: 'https://geoscoreapi.com',
    sourceCategory: 'Text Analysis',
    auth: 'apiKey',
    workflow: 'content-intelligence',
    platformUse: 'Score client pages for AI-search citation readiness.',
    description: 'Score content for AI search citation readiness. Returns a 0-100 GEO score, 8 structural metrics, and improvement fixes',
  },
  {
    name: 'Sentiment Analysis',
    url: 'https://www.meaningcloud.com/developer/sentiment-analysis',
    sourceCategory: 'Text Analysis',
    auth: 'apiKey',
    workflow: 'content-intelligence',
    platformUse: 'Analyze review sentiment and customer feedback themes.',
    description: 'Multilingual sentiment analysis of texts from different sources',
  },
  {
    name: 'GNews',
    url: 'https://gnews.io/',
    sourceCategory: 'News',
    auth: 'apiKey',
    workflow: 'content-intelligence',
    platformUse: 'Monitor client industries and local news for timely campaign angles.',
    description: 'Search for news from various sources',
  },
  {
    name: 'NewsData',
    url: 'https://newsdata.io/docs',
    sourceCategory: 'News',
    auth: 'apiKey',
    workflow: 'content-intelligence',
    platformUse: 'Source fresh local/industry hooks for content briefs and newsletters.',
    description: 'News data API for live-breaking news and headlines from reputed  news sources',
  },
  {
    name: 'Ayrshare',
    url: 'https://www.ayrshare.com',
    sourceCategory: 'Social',
    auth: 'apiKey',
    workflow: 'campaign-delivery',
    platformUse: 'Post and measure social campaigns across client channels.',
    description: 'Social media APIs to post, get analytics, and manage multiple users social media accounts',
  },
  {
    name: 'Mailchimp',
    url: 'https://mailchimp.com/developer/',
    sourceCategory: 'Business',
    auth: 'apiKey',
    workflow: 'campaign-delivery',
    platformUse: 'Send marketing campaigns from generated email sequences.',
    description: 'Send marketing campaigns and transactional mails',
  },
  {
    name: 'PostStack',
    url: 'https://poststack.dev/docs',
    sourceCategory: 'Email',
    auth: 'apiKey',
    workflow: 'campaign-delivery',
    platformUse: 'EU-hosted email delivery option for transactional and marketing sends.',
    description: 'EU-hosted email API for transactional and marketing email, with contacts, broadcasts, and analytics',
  },
  {
    name: 'ClickMeter',
    url: 'https://support.clickmeter.com/hc/en-us/categories/201474986',
    sourceCategory: 'URL Shorteners',
    auth: 'apiKey',
    workflow: 'campaign-delivery',
    platformUse: 'Track, compare, and optimize campaign links Ryan sends or AI publishes.',
    description: 'Monitor, compare and optimize your marketing links',
  },
  {
    name: 'Rebrandly',
    url: 'https://developers.rebrandly.com/v1/docs',
    sourceCategory: 'URL Shorteners',
    auth: 'apiKey',
    workflow: 'campaign-delivery',
    platformUse: 'Create branded short links for campaigns and client reports.',
    description: 'Custom URL shortener for sharing branded links',
  },
  {
    name: 'APITemplate.io',
    url: 'https://apitemplate.io',
    sourceCategory: 'Photography',
    auth: 'apiKey',
    workflow: 'creative-production',
    platformUse: 'Generate templated client creatives, report cards, and PDF/image assets.',
    description: 'Dynamically generate images and PDFs from templates with a simple API',
  },
  {
    name: 'PhotoRoom',
    url: 'https://www.photoroom.com/api/',
    sourceCategory: 'Photography',
    auth: 'apiKey',
    workflow: 'creative-production',
    platformUse: 'Remove backgrounds from client product/team photos for landing pages and ads.',
    description: 'Remove background from images',
  },
  {
    name: 'Open-Meteo',
    url: 'https://open-meteo.com/',
    sourceCategory: 'Weather',
    auth: 'No',
    workflow: 'campaign-delivery',
    platformUse: 'Trigger seasonal HVAC, roofing, plumbing, and storm-response campaign ideas.',
    description: 'Global weather forecast API for non-commercial use',
  },
  {
    name: 'SecurityTrails',
    url: 'https://securitytrails.com/corp/apidocs',
    sourceCategory: 'Security',
    auth: 'apiKey',
    workflow: 'ops-safety',
    platformUse: 'Audit DNS/domain exposure for client-owned assets before publishing recommendations.',
    description: 'Domain and IP related information such as current and historical WHOIS and DNS records',
  },
]

export const PUBLIC_API_WORKFLOW_LABELS: Record<PublicApiWorkflow, string> = {
  'lead-enrichment': 'Lead enrichment',
  'local-seo': 'Local SEO intelligence',
  'content-intelligence': 'Content intelligence',
  'campaign-delivery': 'Campaign delivery',
  'creative-production': 'Creative production',
  'ops-safety': 'Ops safety',
}
